#ifndef DATABASE_SCHEMA_H_
#define DATABASE_SCHEMA_H_

#define SCHEMA " \
CREATE TABLE IF NOT EXISTS TB_SETTINGS ( \
    WEB_SERVER_NAME TEXT, \
    WEB_SERVER_PORT TEXT, \
    DOWNLOAD_DIRECTORY TEXT \
    DOWNLOAD_MAX_ACTIVE TEXT, \
    PROXY_ADDRESS TEXT, \
    PROXY_PORT TEXT, \
    PROXY_ACTIVATE TEXT, \
    PROXY_HTTPS TEXT, \
    DOWNLOAD_MAX_ACTIVE TEXT \
); \
\
CREATE TABLE IF NOT EXISTS TB_SERVERS ( \
    ID_SERVER INTEGER PRIMARY KEY AUTOINCREMENT, \
    URL TEXT, \
    USERNAME TEXT, \
    PASSWORD TEXT, \
    LOGINURL TEXT, \
    LOGINUSERVAR TEXT, \
    LOGINPASSVAR TEXT, \
    PREFIX TEXT, \
    ADDITIONALVARS TEXT \
); \
\
CREATE TABLE IF NOT EXISTS TB_DOWNLOADS ( \
    ID_DOWNLOAD INTEGER PRIMARY KEY AUTOINCREMENT, \
    URL TEXT NOT NULL, \
    FILENAME TEXT NOT NULL, \
    PICTURE_URL TEXT, \
    FOLDER TEXT NOT NULL, \
    STATUS TEXT NOT NULL, \
    DOWNLOADED INTEGER DEFAULT 0, \
    FILESIZE INTEGER DEFAULT 0, \
    COOKIE TEXT, \
    REDIRECTEDURL TEXT, \
    POSITION INTEGER DEFAULT 0 \
);"

#endif  // DATABASE_SCHEMA_H_